name: phuzzy phazer
version: "1.0"
author: Haynes Heaton <whheaton@gmail.com>
about: sparse mixture model diploid and polyploid phasing
args:
    - output:
        long: output
        short: o
        takes_value: true
        required: true
        help: output directory
    - het_kmers:
        long: het_kmers
        short: k
        takes_value: true
        required: true
        help: het_kmers.tsv from het_snp_kmers output
    - linked_read_mols:
        long: linked_read_mols
        short: l
        multiple: true
        takes_value: true
        required: false
        help: linked read molecule kmers from output of molecule_kmers
    - hic_mols:
        long: hic_mols
        short: h
        multiple: true
        required: true
        takes_value: true
        help: hic kmers as output from molecule_kmers 
    - long_read_mols:
        long: long_read_mols
        multiple: true
        required: false
        takes_value: true
        help: long reads as output from molecule_kmers
    - threads:
        short: t
        long: threads
        required: false
        takes_value: true
        help: max number of threads.
    - seed:
        short: s
        long: seed
        required: false
        takes_value: true
        help: random seed
    - restarts:
        long: restarts
        required: false
        takes_value: true
        help: number of random restarts
    - assembly_fasta:
        short: f
        long: assembly_fasta
        required: true
        help: assembly fasta file
        takes_value: true
    - assembly_kmers:
        short: a
        long: assembly_kmers
        required: true
        help: assembly kmers file from molecule_kmers
        takes_value: true
