name: phuzzy phazer
version: "1.0"
author: Haynes Heaton <whheaton@gmail.com>
about: sparse mixture model diploid and polyploid phasing
args:
    - output:
        long: output
        short: o
        takes_value: true
        required: true
        help: output directory
    - het_kmers:
        long: het_kmers
        short: h
        takes_value: true
        required: true
        help: het_kmers.tsv from het_snp_kmers output
    - linked_read_kmers:
        long: linked_read_kmers
        multiple: true
        takes_value: true
        required: false
        help: 10x genomics linked read molecule kmers from output of molecule_kmers
    - hic_kmers:
        long: hic_r1s
        multiple: true
        required: true
        takes_value: true
        help: hic r1 files 
    - threads:
        short: t
        long: threads
        required: false
        takes_value: true
        help: max number of threads. (not yet threaded, for future use)
    - assembly_fasta:
        short: f
        long: assembly_fasta
        required: true
        help: assembly fasta file
        takes_value: true
    - assembly_kmers:
        short: a
        long: assembly_kmers
        required: true
        help: assembly kmers file from molecule_kmers
        takes_value: true
